#!/usr/bin/env python3
"""Installer for /setup-merge-gate (issue #04).

Stdlib only (Python 3.11+ for tomllib). Driven by SKILL.md, which
collects placeholder values from the user and invokes this script
with --target <path> plus a flag per placeholder.

What this writes (under <target>):

  .github/workflows/codex-review.yml      ← rendered from templates/
  docs/merge-gate.md                      ← rendered from templates/
  harness.toml                            ← [merge-gate] section, surgical
  .claude/agents/codex-review-validator.md  ← vendored from ~/.claude/agents/
  .claude/skills/run-codex-validators/      ← vendored from ~/.claude/skills/

--uninstall reverses all of the above (docs are kept iff their
generated marker was tampered with — see DOCS_MARKER).
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path

# --- Constants ----------------------------------------------------------------

SKILL_DIR = Path(__file__).resolve().parent.parent
TEMPLATES = SKILL_DIR / "templates"
GLOBAL_AGENT_SRC = Path("~/.claude/agents/codex-review-validator.md").expanduser()
GLOBAL_RUNTIME_SRC = Path("~/.claude/skills/run-codex-validators").expanduser()

SECTION = "merge-gate"

# Discoverable substring used by --uninstall to detect "still managed by us".
MARKER_TAG = "managed by /setup-merge-gate v1"
HTML_MARKER = f"<!-- {MARKER_TAG}; re-installer will overwrite -->"
HASH_MARKER = f"# {MARKER_TAG}; re-installer will overwrite"
FM_KEY = "managed_by"
FM_VALUE = "/setup-merge-gate v1 (re-installer will overwrite)"

# First-line marker on the docs files we author. --uninstall removes the
# file only if this marker is still present (i.e. user has not taken it over).
DOCS_MARKER = "<!-- generated by /setup-merge-gate v1; do not edit by hand -->"

PLACEHOLDERS = (
    "PROJECT_NAME",
    "SOFT_MODE_DEFAULT",
    "DOCS_ONLY_GLOBS",
    "TRUST_DOC_GLOBS",
    "NODE_VERSION",
    "CODEX_INSTALL_CMD",
    "CODEX_REVIEW_CMD",
    "BYPASS_LABEL",
)

WORKFLOW_REL = ".github/workflows/codex-review.yml"
HARNESS_TOML_REL = "harness.toml"
DOCS_QUICKREF_REL = "docs/merge-gate.md"
VENDOR_AGENT_REL = ".claude/agents/codex-review-validator.md"
VENDOR_SKILL_REL = ".claude/skills/run-codex-validators"
# Codex review-output schema, vendored verbatim from the openai-codex plugin.
# The default codex_review_cmd points `--output-schema` here. CI runners do
# not have the plugin marketplace, so the schema must live inside the target
# repo. JSON has no comment syntax, so the file is written without a marker.
SCHEMA_REL = ".codex-review/schema.json"

OK, ADD, WARN, ERR, REM = "✓", "+", "⚠", "✗", "-"


# --- Output helpers -----------------------------------------------------------


def emit(symbol: str, msg: str) -> None:
    print(f"  {symbol} {msg}")


def section_hdr(name: str) -> None:
    print(f"\n[{name}]")


def die(msg: str, code: int = 1):
    print(f"{ERR} {msg}", file=sys.stderr)
    sys.exit(code)


def check_vendor_symlinks(target: Path) -> None:
    # If a vendored target is a symlink, install would write through it
    # into the externally-pointed tree, and uninstall would rmtree the
    # external tree's contents. Refuse both — make the operator point
    # at a real path first.
    for rel in (VENDOR_AGENT_REL, VENDOR_SKILL_REL):
        path = target / rel
        if path.is_symlink():
            die(
                f"Refusing to operate on {rel}: it is a symlink. "
                "Replace it with a real path (or remove it) before re-running."
            )


# --- Target discovery ---------------------------------------------------------


def find_target(arg: str | None) -> Path:
    base = Path(arg).resolve() if arg else Path.cwd()
    try:
        out = subprocess.run(
            ["git", "-C", str(base), "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            check=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        die(f"Not inside a git repository: {base}")
    return Path(out.stdout.strip())


def require_agents_md(target: Path) -> None:
    if not (target / "AGENTS.md").exists():
        die(
            f"AGENTS.md missing at {target / 'AGENTS.md'}. "
            "Run `/setup-agents-md` first (issue #01).",
            code=2,
        )


# --- TOML helpers -------------------------------------------------------------


def _to_toml_string(s: str) -> str:
    """Pick the simplest TOML string flavour that encodes s losslessly.

    Order of preference: literal single-line ('...'), literal multi-line
    ('''...'''). Falls back to an error if the value contains the multi-line
    terminator — none of our placeholder values realistically do.
    """
    if "'''" in s:
        die(f"Cannot encode TOML value containing triple-single-quote: {s!r}")
    if "'" not in s and "\n" not in s:
        return f"'{s}'"
    # Multi-line literal. Opening newline is trimmed by TOML spec.
    return f"'''\n{s}'''"


def _to_toml_array(items: list[str]) -> str:
    return "[" + ", ".join(_to_toml_string(x) for x in items) + "]"


def emit_section(values: dict) -> str:
    """Render the [merge-gate] section as TOML text, ending with '\\n'."""
    lines = [f"[{SECTION}]"]
    for key_upper in PLACEHOLDERS:
        key = key_upper.lower()
        val = values[key]
        if isinstance(val, list):
            lines.append(f"{key} = {_to_toml_array(val)}")
        else:
            lines.append(f"{key} = {_to_toml_string(val)}")
    return "\n".join(lines) + "\n"


def surgically_replace_section(text: str, section: str, new_block: str) -> str:
    """Replace [section] (header + body up to next [...] or EOF) with new_block."""
    pattern = re.compile(
        rf"^\[{re.escape(section)}\]\s*$\n(.*?)(?=^\[|\Z)",
        re.MULTILINE | re.DOTALL,
    )
    if pattern.search(text):
        return pattern.sub(lambda _m: new_block, text, count=1)
    if text and not text.endswith("\n"):
        text += "\n"
    if text.strip():
        text += "\n"
    return text + new_block


def surgically_remove_section(text: str, section: str) -> str:
    pattern = re.compile(
        rf"^\[{re.escape(section)}\]\s*$\n(.*?)(?=^\[|\Z)",
        re.MULTILINE | re.DOTALL,
    )
    return pattern.sub("", text, count=1)


def verify_no_drift(before: dict, after: dict, owned: str) -> None:
    """Raise if any section other than `owned` changed between before/after."""
    keys = (set(before) | set(after)) - {owned}
    for k in keys:
        if before.get(k) != after.get(k):
            die(
                f"harness.toml surgery would drift section [{k}] (refusing to write). "
                "This is a bug in render.py; please file an issue."
            )


# --- Template rendering -------------------------------------------------------


def render_template(src: Path, tokens: dict[str, str]) -> str:
    text = src.read_text(encoding="utf-8")
    for key in PLACEHOLDERS:
        text = text.replace(f"%%{key}%%", tokens[key])
    leftover = sorted(set(re.findall(r"%%[A-Z_]+%%", text)))
    if leftover:
        die(f"Template {src.name} has unbound placeholders after substitution: {leftover}")
    return text


def tokens_from_values(values: dict) -> dict[str, str]:
    """Convert internal value dict (lists, strings) to the string tokens the
    template substitution expects. docs_only_globs is encoded as compact JSON."""
    tokens: dict[str, str] = {}
    for key in PLACEHOLDERS:
        v = values[key.lower()]
        if isinstance(v, list):
            tokens[key] = json.dumps(v, separators=(",", ":"))
        else:
            tokens[key] = v
    return tokens


# --- Vendoring ----------------------------------------------------------------


def _inject_frontmatter_key(text: str) -> str:
    lines = text.split("\n")
    if not lines or lines[0].rstrip() != "---":
        return None  # no frontmatter
    for i in range(1, len(lines)):
        if lines[i].rstrip() == "---":
            lines.insert(i, f"{FM_KEY}: {FM_VALUE}")
            return "\n".join(lines)
    return None


def add_marker(text: str, suffix: str) -> str:
    """Return text with a discoverable managed-by marker added.

    Frontmatter-bearing markdown gets the marker as a YAML key (top-line
    comment would break the frontmatter parser). Other files get a
    first-line comment in the right syntax.
    """
    if text.startswith(("---\n", "---\r\n")):
        injected = _inject_frontmatter_key(text)
        if injected is not None:
            return injected
    if suffix.lower() in {".md", ".markdown", ".html"}:
        return _prepend_preserving_shebang(text, HTML_MARKER)
    if suffix.lower() in {".py", ".sh", ".bash", ".yml", ".yaml", ".toml", ".cfg", ".ini", ".conf"}:
        return _prepend_preserving_shebang(text, HASH_MARKER)
    # Fallback: hash comment. JSON has no comments — this will be unusable
    # if we ever vendor a .json file, but the runtime skill (#05) has no
    # JSON in its source tree at the time of writing.
    return _prepend_preserving_shebang(text, HASH_MARKER)


def _prepend_preserving_shebang(text: str, marker: str) -> str:
    """Prepend marker as a new first line, but keep an existing shebang on line 1."""
    if text.startswith("#!"):
        shebang, _, rest = text.partition("\n")
        return f"{shebang}\n{marker}\n{rest}"
    return f"{marker}\n{text}"


SKIP_DIRS = {"__pycache__", ".git", "node_modules", ".pytest_cache", ".mypy_cache", ".ruff_cache",
             # Test fixtures live next to the script they exercise (matching the
             # hooks/test_*.py pattern) and have no runtime role — they are dev-only.
             # Vendoring them would also corrupt JSON files because add_marker would
             # prepend a `#`-style comment that JSON does not accept.
             "fixtures"}
SKIP_SUFFIXES = {".pyc", ".pyo", ".so", ".dylib", ".dll"}
SKIP_NAMES = {".DS_Store", "Thumbs.db"}


def _should_skip(src: Path, runtime_src: Path) -> bool:
    rel_parts = src.relative_to(runtime_src).parts
    if any(part in SKIP_DIRS for part in rel_parts):
        return True
    if src.suffix.lower() in SKIP_SUFFIXES:
        return True
    if src.name in SKIP_NAMES:
        return True
    # Skip stdlib-unittest test modules (test_*.py) — dev-only regression
    # suites that should not ship into target repos.
    if src.name.startswith("test_") and src.suffix == ".py":
        return True
    return False


def vendored_files(runtime_src: Path) -> list[tuple[Path, str]]:
    """Return list of (relative_destination, marker-injected content) for every
    text file vendored from runtime_src. Skips caches, VCS dirs, and binaries."""
    out: list[tuple[Path, str]] = []
    for src in sorted(runtime_src.rglob("*")):
        if not src.is_file() or _should_skip(src, runtime_src):
            continue
        rel = src.relative_to(runtime_src)
        dst = Path(VENDOR_SKILL_REL) / rel
        try:
            text = src.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            die(
                f"Refusing to vendor non-UTF8 file from runtime skill: {src} "
                f"(add its extension to SKIP_SUFFIXES if it is a build artefact)."
            )
        out.append((dst, add_marker(text, src.suffix)))
    return out


# --- Install / uninstall ------------------------------------------------------


def parse_globs(raw: str, flag: str = "--docs-only-globs") -> list[str]:
    try:
        v = json.loads(raw)
    except json.JSONDecodeError as exc:
        die(f"{flag} must be a JSON array of strings; parse error: {exc}")
    if not isinstance(v, list) or not all(isinstance(x, str) for x in v):
        die(f"{flag} must be a JSON array of strings")
    return v


def install(target: Path, values: dict, dry_run: bool, runtime_src_override: Path | None) -> None:
    require_agents_md(target)
    check_vendor_symlinks(target)

    agent_src = GLOBAL_AGENT_SRC
    if not agent_src.exists():
        die(
            f"Validator agent source not found at {agent_src}. "
            "Install /codex-review-validator first (issue #02)."
        )

    runtime_src = runtime_src_override or GLOBAL_RUNTIME_SRC
    if not runtime_src.exists() or not runtime_src.is_dir():
        die(
            f"Runtime skill source not found at {runtime_src}. "
            "Install /run-codex-validators first (issue #05), "
            "or pass --validator-runtime-src <path> for testing."
        )

    tokens = tokens_from_values(values)

    # Build all artefacts in memory first.
    artefacts: list[tuple[Path, str]] = []
    artefacts.append((Path(WORKFLOW_REL), render_template(TEMPLATES / "codex-review.yml", tokens)))
    artefacts.append((Path(DOCS_QUICKREF_REL), render_template(TEMPLATES / "merge-gate.md.template", tokens)))
    artefacts.append((Path(VENDOR_AGENT_REL), add_marker(agent_src.read_text(encoding="utf-8"), agent_src.suffix)))
    # Codex review-output schema — verbatim copy, no marker (JSON has no
    # comment syntax). Default `codex_review_cmd` points --output-schema here.
    artefacts.append((Path(SCHEMA_REL), (TEMPLATES / "review-output.schema.json").read_text(encoding="utf-8")))
    artefacts.extend(vendored_files(runtime_src))

    # harness.toml surgery — built separately because of drift check.
    harness_path = target / HARNESS_TOML_REL
    before_text = harness_path.read_text(encoding="utf-8") if harness_path.exists() else ""
    new_text = surgically_replace_section(before_text, SECTION, emit_section(values))
    before_parsed = tomllib.loads(before_text) if before_text else {}
    after_parsed = tomllib.loads(new_text)
    verify_no_drift(before_parsed, after_parsed, owned=SECTION)

    # Plan + report.
    section_hdr("install")
    for rel, content in artefacts:
        path = target / rel
        if path.exists() and path.read_text(encoding="utf-8") == content:
            emit(OK, str(rel))
        else:
            emit(ADD, str(rel))
    if before_text == new_text:
        emit(OK, f"{HARNESS_TOML_REL} [{SECTION}]")
    else:
        emit(ADD, f"{HARNESS_TOML_REL} [{SECTION}]")

    if dry_run:
        emit(WARN, "dry-run — no files written")
        return

    # Commit.
    for rel, content in artefacts:
        path = target / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    harness_path.write_text(new_text, encoding="utf-8")

    print_next_steps()


def print_next_steps() -> None:
    print()
    print("Next steps (HITL — not automated by this skill):")
    print()
    print("  1. Add Actions secrets to the repo on github.com:")
    print("       CLAUDE_CODE_OAUTH_TOKEN  (required — read by Run Claude validator)")
    print("       CODEX_API_KEY            (required — `codex exec` non-interactive auth;")
    print("                                 OPENAI_API_KEY is NOT honored by `codex exec`)")
    print()
    print("  2. Add a branch-protection rule on `main` (and any other protected")
    print("     branch) requiring this check:")
    print()
    print("       merge-gate / codex-review")
    print()
    print("     The check is stable across soft/hard mode flips; do not")
    print("     re-add the rule when promoting.")
    print()
    print("  3. The gate ships in SOFT mode (data collection — never blocks).")
    print("     Flip to HARD only after meeting the promotion criteria. Edit")
    print("     `harness.toml` [merge-gate] soft_mode_default and re-run this")
    print("     installer to push the change into the workflow.")


def uninstall(target: Path, dry_run: bool) -> None:
    section_hdr("uninstall")
    check_vendor_symlinks(target)
    actions: list[tuple[str, Path, str | None]] = []

    # Workflow
    wf = target / WORKFLOW_REL
    if wf.exists():
        actions.append((REM, wf, None))

    # harness.toml [merge-gate]
    harness_path = target / HARNESS_TOML_REL
    new_harness_text: str | None = None
    if harness_path.exists():
        before = harness_path.read_text(encoding="utf-8")
        after = surgically_remove_section(before, SECTION)
        before_parsed = tomllib.loads(before)
        after_parsed = tomllib.loads(after) if after.strip() else {}
        verify_no_drift(before_parsed, after_parsed, owned=SECTION)
        if before != after:
            actions.append((REM, harness_path, after))
            new_harness_text = after

    # Vendored agent + skill dir
    va = target / VENDOR_AGENT_REL
    if va.exists():
        actions.append((REM, va, None))
    vs = target / VENDOR_SKILL_REL
    if vs.exists():
        actions.append((REM, vs, None))

    # Vendored review-output schema
    sch = target / SCHEMA_REL
    if sch.exists():
        actions.append((REM, sch, None))

    # Docs — marker-gated
    for rel in (DOCS_QUICKREF_REL,):
        p = target / rel
        if not p.exists():
            continue
        first = p.read_text(encoding="utf-8").splitlines()[:1]
        if first and DOCS_MARKER in first[0]:
            actions.append((REM, p, None))
        else:
            actions.append((WARN, p, "marker missing — left intact (user-edited)"))

    if not actions:
        emit(OK, "nothing to uninstall")
        return

    for symbol, path, note in actions:
        rel = path.relative_to(target) if path.is_relative_to(target) else path
        if symbol == WARN:
            emit(symbol, f"{rel} — {note}")
        else:
            emit(symbol, str(rel))

    if dry_run:
        emit(WARN, "dry-run — no files removed")
        return

    for symbol, path, content in actions:
        if symbol != REM:
            continue
        if content is not None:
            # harness.toml rewrite
            path.write_text(content, encoding="utf-8")
        elif path.is_dir():
            _rmtree(path)
        else:
            path.unlink()

    # Best-effort cleanup of empty parent dirs we created (.claude/agents/, .claude/skills/, .claude/, .github/workflows/, .github/, docs/, .codex-review/).
    for rel in (
        ".claude/agents",
        ".claude/skills",
        ".claude",
        ".github/workflows",
        ".github",
        "docs",
        ".codex-review",
    ):
        p = target / rel
        if p.exists() and p.is_dir() and not any(p.iterdir()):
            p.rmdir()


def _rmtree(p: Path) -> None:
    for child in sorted(p.iterdir(), reverse=True):
        if child.is_dir():
            _rmtree(child)
        else:
            child.unlink()
    p.rmdir()


# --- CLI ---------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        prog="setup-merge-gate",
        description="Install / uninstall the merge-gate harness into a target project.",
    )
    ap.add_argument("--target", help="Target git repo (default: cwd)")
    ap.add_argument("--dry-run", action="store_true", help="Preview without writing.")
    ap.add_argument("--uninstall", action="store_true", help="Remove the gate's artefacts.")
    ap.add_argument(
        "--validator-runtime-src",
        help="Override path to ~/.claude/skills/run-codex-validators (for testing while #05 is unmerged).",
    )

    # Placeholder flags (required for install, ignored for uninstall).
    ap.add_argument("--project-name", help="%%PROJECT_NAME%%")
    ap.add_argument("--soft-mode-default", choices=["true", "false"], help="%%SOFT_MODE_DEFAULT%%")
    ap.add_argument("--docs-only-globs", help="%%DOCS_ONLY_GLOBS%% (JSON array of strings)")
    ap.add_argument("--trust-doc-globs", help="%%TRUST_DOC_GLOBS%% (JSON array of strings)")
    ap.add_argument("--node-version", help="%%NODE_VERSION%%")
    ap.add_argument("--codex-install-cmd", help="%%CODEX_INSTALL_CMD%%")
    ap.add_argument("--codex-review-cmd", help="%%CODEX_REVIEW_CMD%%")
    ap.add_argument("--bypass-label", help="%%BYPASS_LABEL%%")
    return ap


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    target = find_target(args.target)

    if args.uninstall:
        uninstall(target, dry_run=args.dry_run)
        return 0

    # Install: validate required flags.
    required = {
        "project_name": args.project_name,
        "soft_mode_default": args.soft_mode_default,
        "docs_only_globs": args.docs_only_globs,
        "trust_doc_globs": args.trust_doc_globs,
        "node_version": args.node_version,
        "codex_install_cmd": args.codex_install_cmd,
        "codex_review_cmd": args.codex_review_cmd,
        "bypass_label": args.bypass_label,
    }
    missing = [k for k, v in required.items() if v is None]
    if missing:
        die(f"Missing required flags: {missing}")

    values: dict = {
        "project_name": args.project_name,
        "soft_mode_default": args.soft_mode_default,
        "docs_only_globs": parse_globs(args.docs_only_globs),
        "trust_doc_globs": parse_globs(args.trust_doc_globs, "--trust-doc-globs"),
        "node_version": args.node_version,
        "codex_install_cmd": args.codex_install_cmd,
        "codex_review_cmd": args.codex_review_cmd,
        "bypass_label": args.bypass_label,
    }

    runtime_src = Path(args.validator_runtime_src).resolve() if args.validator_runtime_src else None
    install(target, values, dry_run=args.dry_run, runtime_src_override=runtime_src)
    return 0


if __name__ == "__main__":
    sys.exit(main())
